apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-crud
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-crud
  template:
    metadata:
      labels:
        app: hello-crud
    spec:
      containers:
      - name: hello-crud
        image: 824987503353.dkr.ecr.us-east-2.amazonaws.com/jfrog:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: harness1
---
apiVersion: v1
kind: Service
metadata:
  name: hello-crud
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: hello-crud
