workflows:
  version: 2
  build-test-&-deploy:
    jobs:
      - build

version: 2
jobs:
  build:
    working_directory: ~/project
    machine: true
    steps:
      - checkout

      #  TODO: set up a few unit tests
      # - store_test_results:
      #     path: /home/circleci/projectName/webapp/test-reports

      # - store_artifacts:
      #     path: /home/circleci/projectName/webapp/test-reports


      - run: docker build -t oh-crud .