orbs:
  aws-ecr: circleci/aws-ecr@8.1.2

workflows:
  version: 2.1
  build-test-&-deploy:
    jobs:
      - build

parameters:
  ecr-repo:
    type: string
    default: "foo"


version: 2.1
jobs:
  build:
    environment:
      ECR_REPO: << pipeline.parameters.ecr-repo >>
    working_directory: ~/project
    machine: true
    steps:
      - checkout

      #  TODO: set up a few unit tests
      # - store_test_results:
      #     path: /home/circleci/projectName/webapp/test-reports

      # - store_artifacts:
      #     path: /home/circleci/projectName/webapp/test-reports


      # - run: docker build -t oh-crud .
      - aws-ecr/build-and-push-image:
          repo: $ECR_REPO
