pipeline:
  identifier: Build_aedifex_oh_CRUD_1711568318821
  name: Build oh-CRUD
  orgIdentifier: default
  projectIdentifier: ohCRUD20
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1711406225860
        repoName: aedifex/oh-CRUD
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: Run NPM Install
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: buildimage
                  name: Build Docker Image
                  spec:
                    command: docker build -t harness:local .
                  timeout: ""
                  type: Run
              - step:
                  identifier: tagimage
                  name: Tag Docker Image
                  spec:
                    command: docker tag harness:local 824987503353.dkr.ecr.us-east-2.amazonaws.com/jfrog:latest
                  timeout: ""
                  type: Run
              - step:
                  type: BuildAndPushECR
                  name: BuildAndPushECR_1
                  identifier: BuildAndPushECR_1
                  spec:
                    connectorRef: Aedifex_AWS
                    region: us-east-2
                    account: "824987503353"
                    imageName: jfrog
                    tags:
                      - local
          platform:
            arch: Amd64
            os: Linux
          runtime:
            spec: {}
            type: Cloud
        type: CI

service:
  name: EKS-Demo
  identifier: EKSDemo
  orgIdentifier: default
  projectIdentifier: ohCRUD20
  serviceDefinition:
    type: Kubernetes
    spec:
      artifacts:
        primary:
          type: DockerRegistry
          spec:
            connectorRef: Aedifex_AWS # Reference to your AWS/ECR connector
            imagePath: "824987503353.dkr.ecr.us-east-2.amazonaws.com/jfrog" # Full image path without tag
            tag: local # Use a specific tag or <+input> for dynamic input at runtime
      variables: [] # Define any necessary service variables here
      manifests:
        - manifest:
            type: K8sManifest
            spec:
              store:
                type: Git
                spec:
                  connectorRef: account.Github_OAuth_1711406225860 # Reference to your Git repo connector
                  repoName: aedifex/oh-CRUD
                  folderPath: app.yaml # E.g., "k8s/deploy"
                  branch: master # Specify the branch where your manifests are located

